stages:
  download:
    cmd: .venv/bin/python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download
  build:
    cmd: .venv/bin/python stages/02_build.py
    deps:
      - stages/02_build.py
      - download
    outs:
      - brick
