# example stages
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:
  to-parquet:
    cmd: clj -X biobricks.ecotox/build-parquet '{:db "data/ecotox_ascii" :output "brick"}'
    deps:
      - data/ecotox_ascii
    outs:
      - brick
